PRESSURE_PACKET_STATUS: str = "80"
PRESSURE_PACKET_PRESSURE_VALUE_MIN: float = 0
PRESSURE_PACKET_PRESSURE_VALUE_MAX: float = 65535
PRESSURE_PACKET_CURRENT_VALUE_COUNTER_MIN: int = 0
PRESSURE_PACKET_CURRENT_VALUE_COUNTER_MAX: int = 127
LOGGING_FORMAT: str = "%(asctime)s - %(levelname)s - %(message)s"
SQLITE_DB_PATH: str = "sqlite.db"
