PRESSURE_PACKET_STATUS = "80"
PRESSURE_PACKET_PRESSURE_VALUE_MIN = 0
PRESSURE_PACKET_PRESSURE_VALUE_MAX = 65535
PRESSURE_PACKET_CURRENT_VALUE_COUNTER_MIN = 0
PRESSURE_PACKET_CURRENT_VALUE_COUNTER_MAX = 127
LOGGING_FORMAT = "%(asctime)s - %(levelname)s - %(message)s"
SQLITE_DB_PATH = "sqlite.db"
