name: 'CI'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  DOCKER_IMAGE: '${{ secrets.DOCKER_USERNAME }}/sensor-data-parser:${{ github.ref_name }}'
jobs:
  build-push:
    name: 'Build and push docker image'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_ACCESS_TOKEN }}'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: '${{ env.DOCKER_IMAGE }}'
  check-lint:
    name: 'Check lint'
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Check lint
        run: docker run $DOCKER_IMAGE make check_lint
  coverage:
    name: 'Show coverage'
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Show coverage
        run: docker run $DOCKER_IMAGE make coverage
