name: 'Build and push docker image, lint check and show coverage'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  DOCKER_IMAGE: '${{ secrets.DOCKER_USERNAME }}/sensor-data-parser:${{ github.ref_name }}'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_ACCESS_TOKEN }}'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: '${{ env.DOCKER_IMAGE }}'
      - name: Check lint
        run: docker run $DOCKER_IMAGE make check_lint
      - name: Show coverage
        run: docker run $DOCKER_IMAGE make coverage
